# Generated by Django 2.0.1 on 2018-02-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carver', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
